### ISSUE TITLE
BitSet.js update

### ISSUE THREAD

**Issue by infusion** [MatrixAI/js-resource-counter#1]
Hi,

I'm the author of the bitset.js library you use. I just got the shorter npm name "bitset" instead of "bitset.js". The latter is now deprecated. Could you please update your dependencies? 

Thanks and sorry for any inconveniences
Robert

**Comment by CMCDragonkai** [comment]
The old name still works atm right? Will change it soon.

**Comment by infusion** [comment]
Yes the old name will remain active and will ship the last version. But no updates will go to the old name, like a bug I fixed recently on the `and` function, I figured through fuzzing.

**Comment by CMCDragonkai** [comment]
Hi I've done it now. Thanks!
